# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/CE_128TR/CE_128TR.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR || ORIG_REF_NAME==CE_128TR} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_LowPAPR1_0_0/CE_128TR_LowPAPR1_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_LowPAPR1_0_0 || ORIG_REF_NAME==CE_128TR_LowPAPR1_0_0} -quiet] -quiet

# IP: ip/sin_cos_lp/sin_cos_lp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_cos_lp || ORIG_REF_NAME==sin_cos_lp} -quiet] -quiet

# IP: ip/div_31/div_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_31 || ORIG_REF_NAME==div_31} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_0_0/CE_128TR_Demap_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_0_0 || ORIG_REF_NAME==CE_128TR_Demap_0_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_1_0/CE_128TR_Demap_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_1_0 || ORIG_REF_NAME==CE_128TR_Demap_1_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_2_0/CE_128TR_Demap_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_2_0 || ORIG_REF_NAME==CE_128TR_Demap_2_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_3_0/CE_128TR_Demap_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_3_0 || ORIG_REF_NAME==CE_128TR_Demap_3_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_4_0/CE_128TR_Demap_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_4_0 || ORIG_REF_NAME==CE_128TR_Demap_4_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_5_0/CE_128TR_Demap_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_5_0 || ORIG_REF_NAME==CE_128TR_Demap_5_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_6_0/CE_128TR_Demap_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_6_0 || ORIG_REF_NAME==CE_128TR_Demap_6_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Demap_7_0/CE_128TR_Demap_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Demap_7_0 || ORIG_REF_NAME==CE_128TR_Demap_7_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_0_0/CE_128TR_Correlation_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_0_0 || ORIG_REF_NAME==CE_128TR_Correlation_0_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_1_0/CE_128TR_Correlation_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_1_0 || ORIG_REF_NAME==CE_128TR_Correlation_1_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_2_0/CE_128TR_Correlation_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_2_0 || ORIG_REF_NAME==CE_128TR_Correlation_2_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_3_0/CE_128TR_Correlation_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_3_0 || ORIG_REF_NAME==CE_128TR_Correlation_3_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_4_0/CE_128TR_Correlation_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_4_0 || ORIG_REF_NAME==CE_128TR_Correlation_4_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_5_0/CE_128TR_Correlation_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_5_0 || ORIG_REF_NAME==CE_128TR_Correlation_5_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_6_0/CE_128TR_Correlation_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_6_0 || ORIG_REF_NAME==CE_128TR_Correlation_6_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Correlation_7_0/CE_128TR_Correlation_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Correlation_7_0 || ORIG_REF_NAME==CE_128TR_Correlation_7_0} -quiet] -quiet

# IP: ip/ls_0/ls_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ls_0 || ORIG_REF_NAME==ls_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_1_0/CE_128TR_Average_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_1_0 || ORIG_REF_NAME==CE_128TR_Average_1_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_2_0/CE_128TR_Average_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_2_0 || ORIG_REF_NAME==CE_128TR_Average_2_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_3_0/CE_128TR_Average_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_3_0 || ORIG_REF_NAME==CE_128TR_Average_3_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_4_0/CE_128TR_Average_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_4_0 || ORIG_REF_NAME==CE_128TR_Average_4_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_5_0/CE_128TR_Average_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_5_0 || ORIG_REF_NAME==CE_128TR_Average_5_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_6_0/CE_128TR_Average_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_6_0 || ORIG_REF_NAME==CE_128TR_Average_6_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_7_0/CE_128TR_Average_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_7_0 || ORIG_REF_NAME==CE_128TR_Average_7_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_Average_0_0/CE_128TR_Average_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_Average_0_0 || ORIG_REF_NAME==CE_128TR_Average_0_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_MuxPDU_0_3/CE_128TR_MuxPDU_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_MuxPDU_0_3 || ORIG_REF_NAME==CE_128TR_MuxPDU_0_3} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_gnd1_0/CE_128TR_gnd1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_gnd1_0 || ORIG_REF_NAME==CE_128TR_gnd1_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_0_0/CE_128TR_EstNoise_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_0_0 || ORIG_REF_NAME==CE_128TR_EstNoise_0_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_1_0/CE_128TR_EstNoise_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_1_0 || ORIG_REF_NAME==CE_128TR_EstNoise_1_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_2_0/CE_128TR_EstNoise_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_2_0 || ORIG_REF_NAME==CE_128TR_EstNoise_2_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_3_0/CE_128TR_EstNoise_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_3_0 || ORIG_REF_NAME==CE_128TR_EstNoise_3_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_4_0/CE_128TR_EstNoise_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_4_0 || ORIG_REF_NAME==CE_128TR_EstNoise_4_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_5_0/CE_128TR_EstNoise_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_5_0 || ORIG_REF_NAME==CE_128TR_EstNoise_5_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_6_0/CE_128TR_EstNoise_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_6_0 || ORIG_REF_NAME==CE_128TR_EstNoise_6_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_EstNoise_7_0/CE_128TR_EstNoise_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_EstNoise_7_0 || ORIG_REF_NAME==CE_128TR_EstNoise_7_0} -quiet] -quiet

# IP: ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_0_0/CE_128TR_NoiseAverage_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_0_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_0_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_1_0/CE_128TR_NoiseAverage_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_1_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_1_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_2_0/CE_128TR_NoiseAverage_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_2_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_2_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_3_0/CE_128TR_NoiseAverage_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_3_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_3_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_4_0/CE_128TR_NoiseAverage_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_4_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_4_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_5_0/CE_128TR_NoiseAverage_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_5_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_5_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_6_0/CE_128TR_NoiseAverage_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_6_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_6_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_NoiseAverage_7_0/CE_128TR_NoiseAverage_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_NoiseAverage_7_0 || ORIG_REF_NAME==CE_128TR_NoiseAverage_7_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_0_0/CE_128TR_ChannelNorm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_0_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_0_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_1_0/CE_128TR_ChannelNorm_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_1_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_1_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_2_0/CE_128TR_ChannelNorm_2_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_2_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_2_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_3_0/CE_128TR_ChannelNorm_3_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_3_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_3_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_4_0/CE_128TR_ChannelNorm_4_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_4_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_4_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_5_0/CE_128TR_ChannelNorm_5_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_5_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_5_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_6_0/CE_128TR_ChannelNorm_6_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_6_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_6_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_ChannelNorm_7_0/CE_128TR_ChannelNorm_7_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_ChannelNorm_7_0 || ORIG_REF_NAME==CE_128TR_ChannelNorm_7_0} -quiet] -quiet

# IP: ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_svd_pack_0/CE_128TR_svd_pack_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_svd_pack_0 || ORIG_REF_NAME==CE_128TR_svd_pack_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_svd_fc_0/CE_128TR_svd_fc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_svd_fc_0 || ORIG_REF_NAME==CE_128TR_svd_fc_0} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_svd_0_0/CE_128TR_svd_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_svd_0_0 || ORIG_REF_NAME==CE_128TR_svd_0_0} -quiet] -quiet

# IP: ip/recip_unit/recip_unit.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==recip_unit || ORIG_REF_NAME==recip_unit} -quiet] -quiet

# IP: ip/cordic_rot/cordic_rot.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_rot || ORIG_REF_NAME==cordic_rot} -quiet] -quiet

# IP: ip/cordic_sqrt/cordic_sqrt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_sqrt || ORIG_REF_NAME==cordic_sqrt} -quiet] -quiet

# IP: ip/cordic_vec/cordic_vec.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_vec || ORIG_REF_NAME==cordic_vec} -quiet] -quiet

# IP: bd/CE_128TR/ip/CE_128TR_csi_0_0/CE_128TR_csi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CE_128TR_csi_0_0 || ORIG_REF_NAME==CE_128TR_csi_0_0} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/CE_128TR_ooc.xdc
