# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_EstNoise_3_0/CE_128TR_EstNoise_3_0.xci
# IP: The module: 'CE_128TR_EstNoise_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cmpy_0/cmpy_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/fifo_delay_tdata/fifo_delay_tdata.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_EstNoise_3_0/CE_128TR_EstNoise_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_EstNoise_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_EstNoise_3_0/CE_128TR_EstNoise_3_0.xci
# IP: The module: 'CE_128TR_EstNoise_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cmpy_0/cmpy_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cmpy_0 || ORIG_REF_NAME==cmpy_0} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/fifo_delay_tdata/fifo_delay_tdata.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==fifo_delay_tdata || ORIG_REF_NAME==fifo_delay_tdata} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_EstNoise_3_0/CE_128TR_EstNoise_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_EstNoise_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
