# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/fifo_delay_tdata/fifo_delay_tdata.xci
# IP: The module: 'fifo_delay_tdata' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/ip/fifo_delay_tdata/fifo_delay_tdata_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_tdata'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/fifo_delay_tdata/fifo_delay_tdata.xci
# IP: The module: 'fifo_delay_tdata' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/ip/fifo_delay_tdata/fifo_delay_tdata_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_delay_tdata'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
