# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/div_gen_frac/div_gen_frac.xci
# IP: The module: 'div_gen_frac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/ip/div_gen_frac/div_gen_frac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_frac'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/div_gen_frac/div_gen_frac.xci
# IP: The module: 'div_gen_frac' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/ip/div_gen_frac/div_gen_frac_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'div_gen_frac'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
