# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_svd_0_0/CE_128TR_svd_0_0.xci
# IP: The module: 'CE_128TR_svd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/recip_unit/recip_unit.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==recip_unit || ORIG_REF_NAME==recip_unit} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cordic_rot/cordic_rot.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_rot || ORIG_REF_NAME==cordic_rot} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cordic_sqrt/cordic_sqrt.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_sqrt || ORIG_REF_NAME==cordic_sqrt} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cordic_vec/cordic_vec.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_vec || ORIG_REF_NAME==cordic_vec} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_svd_0_0/CE_128TR_svd_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_svd_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_svd_0_0/CE_128TR_svd_0_0.xci
# IP: The module: 'CE_128TR_svd_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/recip_unit/recip_unit.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==recip_unit || ORIG_REF_NAME==recip_unit} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cordic_rot/cordic_rot.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_rot || ORIG_REF_NAME==cordic_rot} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cordic_sqrt/cordic_sqrt.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_sqrt || ORIG_REF_NAME==cordic_sqrt} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/cordic_vec/cordic_vec.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==cordic_vec || ORIG_REF_NAME==cordic_vec} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_svd_0_0/CE_128TR_svd_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_svd_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
