# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_LowPAPR1_0_0/CE_128TR_LowPAPR1_0_0.xci
# IP: The module: 'CE_128TR_LowPAPR1_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/sin_cos_lp/sin_cos_lp.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_cos_lp || ORIG_REF_NAME==sin_cos_lp} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/div_31/div_31.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_31 || ORIG_REF_NAME==div_31} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_LowPAPR1_0_0/CE_128TR_LowPAPR1_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_LowPAPR1_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_LowPAPR1_0_0/CE_128TR_LowPAPR1_0_0.xci
# IP: The module: 'CE_128TR_LowPAPR1_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/sin_cos_lp/sin_cos_lp.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin_cos_lp || ORIG_REF_NAME==sin_cos_lp} -quiet] -quiet

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/div_31/div_31.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_31 || ORIG_REF_NAME==div_31} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_LowPAPR1_0_0/CE_128TR_LowPAPR1_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_LowPAPR1_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
