# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_ChannelNorm_3_0/CE_128TR_ChannelNorm_3_0.xci
# IP: The module: 'CE_128TR_ChannelNorm_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/div_gen_frac/div_gen_frac.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_ChannelNorm_3_0/CE_128TR_ChannelNorm_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_ChannelNorm_3_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/CE_128TR/CE_128TR.srcs/sources_1/bd/CE_128TR/ip/CE_128TR_ChannelNorm_3_0/CE_128TR_ChannelNorm_3_0.xci
# IP: The module: 'CE_128TR_ChannelNorm_3_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: E:/CE_128TR/CE_128TR.srcs/sources_1/ip/div_gen_frac/div_gen_frac.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==div_gen_frac || ORIG_REF_NAME==div_gen_frac} -quiet] -quiet

# XDC: e:/CE_128TR/CE_128TR.gen/sources_1/bd/CE_128TR/ip/CE_128TR_ChannelNorm_3_0/CE_128TR_ChannelNorm_3_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'CE_128TR_ChannelNorm_3_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
